### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by moorthi07**
Website admin Dashboard  to a Json object array
Updated website to English
Updated - docs, added pics

### CODE REVIEW

**Comment by rgolea** [comment]
Thanks a lot! I will try and fix this repo soon! Good job and nice work!

**Comment by moorthi07** [comment]
Hey, Cool. Wondering why Fontawsome is not working if added to bowercomponents. Debugging, but did you try before?

**Comment by rgolea** [comment]
I think you need to set up a proper grunt task. Anyways... Keep up the good work! I will refactor this project when I have some time.

Thanks!

**Comment by moorthi07** [comment]
Grunt changed, but not that is the issue. I tried many combinations, some thing is blocking the icon rendering (it only displays a square block).

**Comment by rgolea** [comment]
Has to be in the same relative path from the css. I've got the feeling it can't find the files.

**Comment by moorthi07** [comment]
issue is this .woff  -  and the folder it is looking for is in the root -> http://localhost:2403/fonts/fontawesome-webfont.woff2?v=4.6.2  . -- This happens only in   'public/dist'  to deploy after the grunt tasks cancat, min, copy!  sounds like path problem not working with our grunt work flow and deployment folders.

**Pull request merged**
